// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/com/android/dialer/logging/people_api_lookup_error.proto

package com.android.dialer.logging;

public interface PeopleApiLookupErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.dialer.logging.PeopleApiLookupError)
    com.google.protobuf.MessageLiteOrBuilder {
}
