// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/com/android/dialer/logging/video_tech.proto

package com.android.dialer.logging;

public interface VideoTechOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.android.dialer.logging.VideoTech)
    com.google.protobuf.MessageLiteOrBuilder {
}
